### PR TITLE
change queue channel embed message

### LINKED ISSUE #12: Text for queue all
Currently, you can !queue all but there is no way a user can know with the current queue so a small message to let them know.

### PR DESCRIPTION
**Pull request by adamschachne**
closes #12

### CODE REVIEW

**Comment by adamschachne** [comment]
image

**Review by classBabacar — COMMENTED** [review]
Do we need "All non-queue messages are deleted"?

**Comment by adamschachne** [comment]
> Do we need "All non-queue messages are deleted"?

Players usually figure that out the hard way, so maybe not

**Comment by adamschachne** [comment]
image

**Comment by THEASIANDUDE** [comment]
so sorry but is there anyway I could get help with setup? docker looks like its working but the bot doesn't go online

**Comment by adamschachne** [comment]
> so sorry but is there anyway I could get help with setup? docker looks like its working but the bot doesn't go online

It could be that you have not enabled the `Server Members` and `Message Content` gateway intents on your Discord bot. Double check your container logs.

I've opened up [Discussions on this repo](https://github.com/adamschachne/inhouse_bot/discussions/categories/q-a) to use for questions like these.

**Pull request merged**
